package ui

func getTerrainOptions() []string {
	return []string{
		"1 (Coast)",
		"2 (Ocean)",
		"3 (Field)",
		"4 (Mountain)",
		"5 (Forest)",
		"6 (Ice)",
	}
}

func getClimateOptions() []string {
	return []string{
		"1 (Xin-xi)",
		"2 (Imperius)",
		"3 (Bardur)",
		"4 (Oumaji)",
		"5 (Kickoo)",
		"6 (Hoodrick)",
		"7 (Luxidoor)",
		"8 (Vengir)",
		"9 (Zebasi)",
		"10 (Ai-Mo)",
		"11 (Aquarion)",
		"12 (Quetzali)",
		"13 (Elyrion)",
		"14 (Yadakk)",
		"15 (Polaris)",
		"16 (Cymanti)",
	}
}

func getResourceSelectOptions() []string {
	return []string{
		"None",
		"1 (Game)",
		"2 (Crop)",
		"3 (Fish)",
		"4 (Whale)",
		"5 (Metal)",
		"6 (Fruit)",
		"7 (Spores)",
		"8 (Starfish)",
		"9 (Aquacrop)",
	}
}

func getImprovementOptions() []string {
	return []string{
		"None",
		"1 (City)",
		"2 (Ruin)",
		"3",
		"4 (Customs House)",
		"5 (Farm)",
		"6 (Windmill)",
		"7",
		"8 (Port)",
		"9",
		"10",
		"11",
		"12  (Lumber Hut)",
		"13",
		"14",
		"15",
		"16",
		"17 (Temple)",
		"18 (Forest Temple)",
		"19 (Water Temple)",
		"20 (Mountain Temple)",
		"21 (Mine)",
		"22 (Forge)",
		"23 (Altar of Peace)",
		"24 (Tower of Wisdom)",
		"25 (Grand Bazaar)",
		"26 (Emperor's Tomb)",
		"27 (Gate of Power)",
		"28 (Park of Fortune)",
		"29 (Eye of God)",
		"30",
		"31",
		"32",
		"33 (Outpost)",
		"34 (Ice Bank)",
		"35 (Ice Temple)",
		"36",
		"37 (Fungi)",
		"38",
		"39 (Mycelium)",
		"40",
		"41",
		"42",
		"43",
		"44",
		"45",
		"46",
		"47 (Lighthouse)",
		"48 (Bridge)",
		"49 (Aquafarm)",
		"50 (Market)",
		"51",
	}
}

func getUnitTypeOptions() []string {
	return []string{
		"None",
		"1 (Scout)",
		"2 (Warrior)",
		"3 (Rider)",
		"4 (Knight)",
		"5 (Defender)",
		"6 (Ship)",
		"7 (Battleship)",
		"8 (Catapult)",
		"9 (Archer)",
		"10 (Mind Bender)",
		"11 (Swordsman)",
		"12 (Giant)",
		"13 (Bunny)",
		"14 (Boat)",
		"15 (Polytaur)",
		"16 (Navalon)",
		"17 (Dragon Egg)",
		"18 (Baby Dragon)",
		"19 (Fire Dragon)",
		"20 (Amphibian)",
		"21 (Tridention)",
		"22 (Mooni)",
		"23 (Battle Sled)",
		"24 (Ice Fortress)",
		"25 (Ice Archer)",
		"26 (Crab)",
		"27 (Gaami)",
		"28 (Hexapod)",
		"29 (Doomux)",
		"30 (Phychi)",
		"31 (Kiton)",
		"32 (Exida)",
		"33 (Centipede)",
		"34 (Segment)",
		"35 (Raychi)",
		"36 (Shaman)",
		"37 (Dagger)",
		"38 (Cloak)",
		"39 (Cloak Boat)",
		"40 (Pirate)",
		"41 (Bombership)",
		"42 (Scoutship)",
		"43 (Transportship)",
		"44 (Rammership)",
		"45 (Juggernaut)",
	}
}

func getPlayerTribeOptions() []string {
	return []string{
		"2 (Ai-Mo)",
		"3 (Aquarion)",
		"4 (Bardur)",
		"5 (Elyrion)",
		"6 (Hoodrick)",
		"7 (Imperius)",
		"8 (Kickoo)",
		"9 (Luxidoor)",
		"10 (Oumaji)",
		"11 (Quetzali)",
		"12 (Vengir)",
		"13 (Xin-xi)",
		"14 (Yaddak)",
		"15 (Zebasi)",
		"16 (Polaris)",
		"17 (Cymanti)",
	}
}
